### ISSUE TITLE
Opens Notepad, instead of running command.

### ISSUE THREAD

**Issue by sfja2004** [benawad/tsconfig.json#23]
When i type `npx tsconfig.json` and hit enter, a notepad called `tsconfig.json` opens containing:
```shell
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/node_modules/tsconfig.json/src/index.js" "$@"
else 
  exec node  "$basedir/node_modules/tsconfig.json/src/index.js" "$@"
fi
```
The shell waits while the notepad is open. The shell now contains:
```cmd
C:\Users\simon>npx tsconfig.json

C:\Users\simon>
```
This is the case for
 * CMD
 * CMD Admin
 * PowerShell
 * Git Bash

On a Windows 10 Desktop
I don't know if this is a problem on my end.

**Comment by jasonkarjadi** [comment]
I'm also having this issue

**Comment by Gricardov** [comment]
Any solution?

**Comment by wolflu05** [comment]
same issue but with vscode instead of notepad

**Comment by taqace** [comment]
Anyone find a solution to this yet?

**Comment by Gricardov** [comment]
If you are following benawad's course, just copy the code instead of generating it. Don't stop, chamos!

**Comment by BronzW** [comment]
#18

**Comment by BronzW** [comment]
It's because it's mistaking the tsconfig.json script for a json file (because of the file ending) and opens it with your default editor.

**Comment by sfja2004** [comment]
I haven't tested it yet.

But if the problem resides in Windows default file applications. A fix could be to unset default application for *.json files (notepad in my case). Here's an article on how to reset default file application: [answers.microsoft.com](https://answers.microsoft.com/en-us/windows/forum/all/how-to-remove-default-apps-to-open-files/091079d9-11fa-4d9e-b992-abed1bacae01). Default application for *.json is unset by default, and (at least in my case) is set by the user manually.

This approach could be a little naive, as the problem ultimately resides with npx and the way npx handles file execution. And as such this fix may not fix the problem. As I said, I have not tested if it works.

**Comment by OmgImAlexis** [comment]
Duplicate of https://github.com/benawad/tsconfig.json/issues/47

**Comment by sfja2004** [comment]
Closing issue because of duplicates.

Solution: https://github.com/benawad/tsconfig.json/issues/18#issuecomment-805215648

**Comment by OmgImAlexis** [comment]
@SimonFJ20 see my comment. That’s not a good solution. https://github.com/benawad/tsconfig.json/issues/47#issuecomment-1061183881
