### ISSUE TITLE
Remote reading

### ISSUE THREAD

**Issue by timthedev07** [benawad/tsconfig.json#42]
Hi Ben, I'm planning to change the way we read and write config files. I feel like downloading the scripts along with the files is a little bit redundant, and I am not sure if it would be a good idea to stick the files in your github repo and read it using the github api which will effectively reduce the size.

**Comment by benawad** [comment]
the tsconfig files aren't that big, the extra complexity is not worth it

**Comment by timthedev07** [comment]
Awesome, thanks!
