### ISSUE TITLE
feat: pull tsconfig from public github repos

### ISSUE THREAD

**Issue by 41y08h** [benawad/tsconfig.json#44]
Hey Ben, this project would be a lot nicer if it has a feature of pulling tsconfig.json from any public GitHub repo that has it. This way everyone can use this package to create "your opinionated" and "`<user>` opinionated" tsconfig.

## Example 
```bash
npx tsconfig.json -t benawad:dogehouse/baklava/tsconfig.json
npx tsconfig.json -t 41y08h:jstube-api
```

Looking forward to this feature, thanks.

**Comment by timthedev07** [comment]
Can you explain a little bit more about your second example?

**Comment by 41y08h** [comment]
Yes, that's [a repo ](https://github.com/41y08h/jstube-api) URI from which it's intended to pull the `tsconfig.json` in the second example, the whole idea here is to pull the `tsconfig.json` from a repo rather than only imposing a `tsconfig.json` to every typeof project.

In the first example, I've explicitly mentioned the path of the `tsconfig.json` in the repo's branch but in the second example, I've just specified the root of the repo.

## URI structure
```
npx tsconfig.json -t <github-username>:<repo-name><tsconfig-path>
// <tsconfig-path> can be omitted for root path.
```

**Comment by 41y08h** [comment]
@benawad what's your thought on implementing this? Should I make a PR?

**Comment by benawad** [comment]
you might as well just copy paste if you are going to point it at a url

**Comment by 41y08h** [comment]
1. copy-pasting from GitHub takes a lot of time as compared to using CLI.
2. It's URI and not URL. It's short and that's why it's easier.

**Comment by 41y08h** [comment]
> you might as well just copy paste if you are going to point it at a url

My idea is not what you understood I guess - 
1. copy-pasting from GitHub takes a lot of time as compared to using CLI.
2. It's URI and not URL. It's short and that's why it's easier.

Let's see what's easier taking in mind that [this repo's](https://github.com/benawad/express-gql) tsconfig.json is not generated by `npx tsconfig.json`.

## Copy-pasting

**Comment by 41y08h** [comment]
> you might as well just copy paste if you are going to point it at a url

My idea is not what you understood I guess -

1. copy-pasting from GitHub takes a lot of time as compared to using CLI.
2. It's URI and not URL. It's short and that's why it's easier.

Let's see what's easier in creating a new `tsconfig.json` for some project taking in mind that [this repo's](https://github.com/benawad/express-gql) (benawad/express-gql) tsconfig.json is not generated by `npx tsconfig.json` default template and the user wants to use this repo's tsconfig.json.

### Copy-pasting
1. Open Github.
2. Go to the repo page.
3. Open tsconfig.json.
4. Create a new tsconfig.json file.
5. Copy-paste

**OR**

Bookmark that link and -
1. Open link.
2. Create a new tsconfig.json file.
3. Copy-paste.

### Suggested way
1. `npx tsconfig.json -t benawad:express-gql`

_That's it. Easy Peasy!_

**Comment by 41y08h** [comment]
@benawad (just to confirm you read my reply)
