### ISSUE TITLE
Node versions

### ISSUE THREAD

**Issue by Koala-gentil** [benawad/tsconfig.json#8]
The tsconfig for node is not optimal if using node v14.
Could we add new configs suffixed with node version ?
And maybe we could use `process.version` to infer the correct config.

More information about optimal tsconfig for node v14 can be found [here](https://stackoverflow.com/questions/61305578/what-typescript-configuration-produces-output-closest-to-node-js-14-capabilities/61305579#61305579)

I can do a PR, if you are ok with that

**Comment by benawad** [comment]
that sounds great, would love a PR!
